# ------------------------------------------------------------------- #
#                        ___         __           __                  #
#    ____  ____  ____ _ /   | __  __/ /_____     / /____  _________ _ #
#   / __ \/ __ \/ __ `/ /| | / / / / __/ __ \   / __/ _ \/ ___/ __ `/ #
#  / /_/ / /_/ / /_/ / ___ |/ /_/ / /_/ /_/ /  / /_/  __/ /  / /_/ /  #
# / .___/\____/\__, /_/  |_|\__,_/\__/\____/   \__/\___/_/   \__,_/   #
#/_/         /____/                                                   #
#                                                                     #
#                      Created by MrReZik                             #
# ------------------------------------------------------------------- #

# --------------------
# Настройки Валют
# --------------------

# Множитель стоимости.
# Итоговая цена = (Ценность артефакта) * (points-per-value)
# Пример: Ценность 1.5, Множитель 100 -> 150 очков.
points-per-value: 100

# Названия валют, которые используются в плейсхолдере %currency% в лоре.
# Названия должны соответствовать ключам в секции 'artefacts' -> 'currency' (VAULT или PLAYER_POINTS)
currency-names:
  PLAYER_POINTS: "<#FFFF55>Очков"
  VAULT: "<#55FF55>$"

# --------------------
# Рост Артефактов
# --------------------
artefact-growth:
  # Включить "созревание" артефактов в инвентаре?
  enabled: true
  # Как часто (в минутах) ценность будет увеличиваться.
  interval-minutes: 60
  # На сколько увеличивать ценность (0.1 = +0.1 к ценности).
  value-increase: 0.1
  # Максимальная ценность, до которой может "дорасти" артефакт.
  # Установите -1, чтобы убрать лимит.
  max-value: 10.0

# --------------------
# Шаблоны Артефактов
# --------------------
artefacts:
  # 'ancient_shard' - это ID артефакта. Используется в /art give ancient_shard ...
  'ancient_shard':
    material: "AMETHYST_SHARD"
    display_name: "<#AA00AA>Древний Осколок"
    # За какую валюту обменивается этот предмет?
    # Доступные опции: PLAYER_POINTS или VAULT
    currency: "PLAYER_POINTS"
    value:
      # Ценность будет сгенерирована случайно в этом диапазоне
      min: 1.0
      max: 5.0
    lore:
      - "<#FFFFFF>Этот осколок пульсирует"
      - "<#FFFFFF>древней энергией."
      - ""
      - "<#AAAAAA>Ценность: <#FF5555>%chance%"
      - "<#AAAAAA>Цена обмена: <#FF5555>%cost% %currency%" # %currency% возьмет "Очков" из 'currency-names'

  'cursed_coin':
    material: "GOLD_NUGGET"
    display_name: "<#E0E000>Проклятая Монета"
    # Этот артефакт будет обмениваться на валюту Vault (экономика)
    currency: "VAULT"
    value:
      min: 5.0
      max: 15.0
    lore:
      - "<#FFFFFF>Кажется, она что-то шепчет..."
      - ""
      - "<#AAAAAA>Ценность: <#FF5555>%chance%"
      - "<#AAAAAA>Цена обмена: <#FF5555>%cost% %currency%" # %currency% возьмет "$" из 'currency-names'

# --------------------
# Сообщения
# --------------------
# Сообщение для /art help
help-message:
  - "<#AA0000>==================[ <#FF5555>Artefacts <#AA0000>]=================="
  - " "
  - " <#FFFFFF>/art open <#AAAAAA>- Открыть меню обмена."
  - " <#FFFFFF>/art help <#AAAAAA>- Показать это сообщение."
  - " "
  - " <#FF5555>Админ-команды:"
  - " <#FFFFFF>/art give <id> <игрок> <кол-во> <#AAAAAA>- Выдать артефакт."
  - " <#FFFFFF>/art reload [all|config|menu] <#AAAAAA>- Перезагрузить плагин."
  - " "
  - "<#AA0000>=================================================="

# Сообщения для обмена
messages:
  exchange_no_item: "<#FF5555>Возьмите артефакт на курсор, чтобы обменять!"
  exchange_not_artefact: "<#FF5555>Это не артефакт!"
  exchange_no_value: "<#FF5555>Ошибка: не удалось прочитать ценность артефакта."
  exchange_currency_not_found: "<#FF5555>Ошибка: не удалось определить валюту этого предмета. (Тип: %type%)"
  exchange_api_error: "<#FF5555>Произошла ошибка при начислении валюты. Попробуйте позже."
  # Плейсхолдеры: %amount%, %currency%
  exchange_success: "<#55FF55>Вы успешно обменяли артефакт на <#FFFFFF>%amount% %currency%<#55FF55>!"

# Сообщения о запрете
block_place_denied: "<#FF5555>Вы не можете ставить артефакты!"

# Сообщения команд
command:
  no_permission: "<#FF5555>У вас нет прав."
  only_player: "<#FF5555>Только игрок может выполнить эту команду."
  menu_opened: "<#55FF55>Меню обмена артефактов открыто."
  give_usage: "<#AAAAAA>Использование: <#FFFFFF>/art give <id> <игрок> <кол-во>"
  player_not_found: "<#FF5555>Игрок <#FFFFFF>%player%<#FF5555> не найден онлайн."
  invalid_amount: "<#FF5555>Количество должно быть целым положительным числом."
  artefact_not_found: "<#FF5555>Артефакт с ID '<#FFFFFF>%id%<#FF5555>' не найден в config.yml."
  give_success_sender: "<#55FF55>Вы успешно выдали артефакт <#FFFFFF>%player%<#55FF55>."
  give_success_target: "<#55FF55>Вы получили артефакт!"
  reload_usage: "<#AAAAAA>Использование: <#FFFFFF>/art reload [all|config|menu]"
  reload_all: "<#55FF55>Плагин Artefacts (config, menu, tasks) полностью перезагружен."
  reload_config: "<#55FF55>Config.yml и шаблоны артефактов перезагружены."
  reload_menu: "<#55FF55>Menu.yml перезагружен."